### ISSUE TITLE
Unable to connect screencast

### ISSUE THREAD

**Issue by mariusrak** [uxifiit/UXC#36]
At http://www.umediaserver.net/umediaserver/download.html I cannot find `UScreenCapture` so I've tried installing `Unreal Media Server` and `Unreal Live Server` but I cannot connect the UXC to screen cast.
So how can I make it work?
Also is there no other way for allowing screen cast except this external dependency?

**Comment by martinkonopka** [comment]
The link seems to be incorrect, UScreenCapture is on the [Multimedia Components](http://www.umediaserver.net/components/index.html) page on the same site.

**Comment by mariusrak** [comment]
Okay, I've find the UScreenCapture, but UXC is still not connecting to screencast.
There has to be better way to record screen. Some binary that would do so together with the UXC.

**Comment by martinkonopka** [comment]
UScreenCapture is such binary :-) There are other options, of course, but at the time this seemed to fulfill requirements for the screencast recording module. If you have better alternative, you can recommend it for sure. 

Which version have you installed? Try the x86 version, if x64 is not recognized.

**Comment by mariusrak** [comment]
I've meant something that would be packed together with UXC.
The x86 version works. Thanks,
