### ISSUE TITLE
Recording not stored

### ISSUE THREAD

**Issue by mariusrak** [uxifiit/UXC#38]
I wanted to test the example timeline setup. I've started UXC as an administrator. Then I've copied example, but excluded everything with eye-tracker and imported created json. The session started and was executed properly. All devices are connected, firewall prompt on ffmpeg appeared and I've allowed it. But after session I cannot find any records. In _recording_ tab are no "no previous recordings". Am I doing something wrong or is there some bug?
Thanks.

**Comment by martinkonopka** [comment]
Can you post your session definition JSON for replication?
I see the examples on Wiki miss the mention about specifying `recorders` section, which must be set explicitly in the current version of UXC. 

Try adding this member to the root session definition object:
```
{
    "project" : "News reading experiment",
    "name" : "Pilot session",
    "recorders": [
        {
            "name": "Local"
        }
    ],
    ...
}
```

This configures the session recording to store data locally. Sorry for this mistake in Wiki, we plan to revise it in the following days.

**Comment by mariusrak** [comment]
Helped. Thanks.
